INSERT INTO papeis (id, nome) VALUES (1, 'ADM') ON CONFLICT (id) DO NOTHING;
INSERT INTO papeis (id, nome) VALUES (2, 'PEDAGOGICO') ON CONFLICT (id) DO NOTHING;
INSERT INTO papeis (id, nome) VALUES (3, 'RECRUITER') ON CONFLICT (id) DO NOTHING;
INSERT INTO papeis (id, nome) VALUES (4, 'PROFESSOR') ON CONFLICT (id) DO NOTHING;
INSERT INTO papeis (id, nome) VALUES (5, 'ALUNO') ON CONFLICT (id) DO NOTHING;