CREATE TABLE IF NOT EXISTS papeis (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS usuarios (
    id SERIAL PRIMARY KEY,
    login VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(60) NOT NULL UNIQUE,
    papel_id BIGINT NOT NULL REFERENCES papeis(id)
);

CREATE TABLE IF NOT EXISTS docentes (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    dataEntrada DATE NOT NULL DEFAULT current_date,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS cursos (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(250) NOT NULL UNIQUE
);